### ISSUE TITLE
https://github.com/pierreozoux/housescrap

### ISSUE THREAD

**Issue by pierreozoux** [Dremora/apartment-search-webapp#1]
:)

An other abandonned project!

**Comment by Dremora** [comment]
Actually, now I remember you were doing similar — I will check it out! This one is just a frontend — I'll publish the actual scraping part later.

**Comment by pierreozoux** [comment]
it was just as a quick reminder :) If you want to work with me, I'm still interested in this :) The scraping is made in Python, but we could use node also :)

I close this for now.
